num = int(input('Digite um número de 0 a 9999: '))
n = str(num)
separacao = " ".join(n)
divisao = separacao.split()
u = (divisao[3])
d = (divisao[2])
c = (divisao[1])
m = (divisao[0])
print('O número digitado foi {}'.format(n))
print('Unidade {}'.format(u))
print('Dezena {}'.format(d))
print('Centena {}'.format(c))
print('Milhar {}'.format(m))

